### ISSUE TITLE
Device status 

### ISSUE THREAD

**Issue by naza-dev** [NorthernMan54/homebridge-heyu#1]
Hi I'm very new to GitHub so apologies if if this is the wrong place for this. I have recently installed homebridge and homebridge-heyu plugin.  all working within HomeKit with just one minor annoyance which is the status of the x10 appliance modules when set from a scene within iOS/Apple Watch. HomeKit seems to forget the status and then gets confused later on as to what status a x10 unit is.

Given that these devices don't actually support status (or at least mine don't)  I seem to remember heyu keeping a record somehow of what had been sent out as a command so therefore "knowing" that a1 was in "on" state.

In the to do it mentions remote status and status generally I'm assuming this is not implemented yet thus my issue. 

Other than that it's working well with no crash since build. (4 days) 

Sys info:
Raspberry Pi 2
Rasbian Jessie (latest build)
Node 4.2.6
Hardware interface: CM11a via Ftdi based USB serial interface.

Naza

**Comment by NorthernMan54** [comment]
Hi Naza,

For the state of a device, I'm pulling that from heyu directly.  If you check the log file from home bridge, you should see items like "Got power state of A1 1", which is the response from a 'heyu onstate a1'. 

In your scene, when you turn on or off the appliance module, are access the module directly or are you using a macro?  Reason I ask, is I see a similar behaviour when using macro's versus addressing the device directly in a scene.

Also, what client are you using?   With eve version 1.x, I have seen the client update device status from heyu everytime you go to a new screen, while with version 2.x it only updates when you pull down a screen.   Need to do more digging to see if this behaviour is a bug or a feature of homekit/eve.

**Comment by naza-dev** [comment]
I have tried a couple of Apps (prior to the launch the Apple Home app- Demoed at WWDC 2016 later in the year).  The one I find the best at the moment is one called "Home - Smart Home Automation"  by Mathias Hochgatterer.

I feel really dumb now as on closer inspection i was not running the heyu engine - DOH!

Started that, restarted homebridge and bingo!  The status of the x10 devices now updates home kit apps on other devices!

I have erased the ROM on the CM11a now as I want to be clear on whats activating devices rather than the CM11a running macros from memory (off my previous non homebridge/homekit installation)

I have checked activating a couple of scenes and all still seems good with device status updating on other iOS devices. I can't seem to break it at the moment.  Although i have yet to test a RF remote which I'm expecting to fail as i don't  think x10 command listening has been implemented yet.

**Comment by NorthernMan54** [comment]
Tks for the update, I will add a comment about starting the engine in the next version of the readme.  For the monitoring other remotes, I'm just in the process of finalizing the change, so check back in a couple of days and you should that see implemented as well.
