### ISSUE TITLE
allon, alloff?

### ISSUE THREAD

**Issue by travisw-ugcs** [NorthernMan54/homebridge-heyu#10]
Hi NorthernMan,
I've really enjoyed using your plugin!
Is it possible to implement the heyu allon, alloff, lightson, or lightsoff commands on a a house code other than A? I have a neighbor...

**Comment by NorthernMan54** [comment]
No problem, what is the best way to set the house code setting, read it from /etc/heyu/x10.conf and the setting HOUSECODE?

**Comment by travisw-ugcs** [comment]
I would think that’s the easiest.

**Comment by NorthernMan54** [comment]
@travisw-ugcs Just made the changes, please re-install and try again.

**Comment by travisw-ugcs** [comment]
It’s exquisite! 
Thanks!
