### ISSUE TITLE
Problems with dimming

### ISSUE THREAD

**Issue by keithws** [NorthernMan54/homebridge-heyu#15]
Specifically, when you set the brightness via the Home app, it typically changes a moment later with the "real" brightness. I'm thinking a whole integer for `minStep`, 5 is working pretty well for lamp modules with 22 dim levels. However, I'm still having issues where the "real" brightness updates a moment later to a lower value than what I selected. For example, select 25%, but get 20%.

This is complicated by the very nature of dimming in X10.

Also, if a lamp module with soft-start is told to turn on and then a dim command is sent before the soft-start completes, then the dim command interrupts the soft-start and the device is dimmed lower than expected.

I have a bit of code started, but nothing committed yet.

**Comment by NorthernMan54** [comment]
Tks Keith, in my setup I mostly use insteon switches, which if I recall correctly use 32 steps

**Comment by keithws** [comment]
Yes, you are correct, I have two of those switches. If I remember correctly, there is another type of switch with 64 levels as well. There are also switches with preset levels too. I hope to find something that works well for most types of dimmer modules.

In my testing, setting the dimmer level to snap to 5% increments increased WAF, wife approval factor.

For the Insteon switches, my plan is to test changing the brightness value type from integer to float and keep the step value at 3.125. I’m curious to see what values show up in the Home app. Will we get values like 9.375% and 62.5%?

**Comment by NorthernMan54** [comment]
Lately for myself, I have stopped using the Home app for control of any devices and have switched to using Alexa to control all my homebridge devices.  It avoids the slider WAF issue.  Now my only WAF issue, is the asking me to tell Alexa what to do.

**Comment by keithws** [comment]
We also use voice control often, but we have little ones and around bedtime we like to use the app. Any objections to me working  on this?

**Comment by NorthernMan54** [comment]
Not at all sir,  I hope you don’t find the codebase too flakey. It was my first JavaScript program and first homebridge plugin in one.
