### ISSUE TITLE
Ignore remotes and other valid Heyu devices that are useless in Homebridge

### ISSUE THREAD

**Issue by drmessano** [NorthernMan54/homebridge-heyu#6]
Right now I have accessories in Homebridge for my Palmpads and Stick-on remotes that are unsupported and not needed in Homebridge.   They are just sitting there in the default room, useless.  It would be nice to exclude these from being parsed and added.  Could either exclude any devices that are not already defined in the code, or set a config option to exclude by housecode.

**Comment by NorthernMan54** [comment]
Can you share the portion of your x10.conf containing the device aliases?  I want to see what is happening, and could you point out which devices you believe should be excluded.  Tks
