### ISSUE TITLE
[Heyu] Heyu onstate function failed: Error: Command failed: /usr/local/bin/heyu onstate K8 State engine is not running.

### ISSUE THREAD

**Issue by tommyd75** [NorthernMan54/homebridge-heyu#9]
I have it running when I manually start the hey engine but if I reboot the pi it crashes the heyu portion....
"Heyu onstate function failed: Error: Command failed: /usr/local/bin/heyu onstate K8
State engine is not running."

I have to stop the homebridge service and manually start the engine, then restart the service.

I have the START_ENGINE AUTO inside the config file, I think this is all I need right?
Or should I have a script that starts the engine by itself?

**Comment by NorthernMan54** [comment]
@tommyd75 Once I strip all the comments from mine, it looks like this.  And I START_ENGINE AUTO

```
cat /etc/heyu/x10.conf | grep -v "^#" | grep -v "^$"
TTY	/dev/ttyUSB0
START_ENGINE  AUTO
POWERFAIL_UPDATE YES
HOUSECODE	  A                # A B C D E F G H I J K L M N O P
ALIAS Front_Porch A1 StdLM
ALIAS Garden_Path A2 StdAM
ALIAS Side_Door A3 StdLM
ALIAS Rear_Door A4 SL2LM 
ALIAS Family_room_Pot_lights A5 SL2LM ONLEVEL RESUME
ALIAS Family_room_Lamp A6 StdLM
ALIAS Family_room_outlet A7 StdAM
ALIAS Front_Door A8 SL2LM ONLEVEL RESUME
ALIAS Basement A9 SL2LM ONLEVEL RESUME
ALIAS Kitchen_Counter A11 StdLM
ALIAS Living_Room_Lamp A13 StdLM
ALIAS Staircase_Lamp A14 StdAM
ALIAS Powder_Room A15 StdLM
ALIAS Garage_Outlet A16 StdAM
ALIAS Porch_Motion B3 MS14 RFIGNORE
ALIAS Porch_Motion_LS B4 MS14A RFIGNORE
ALIAS Stereo B9 StdAM 
LOG_DIR  /var/log/heyu/
SCRIPT B* alloff :: heyu alloff A
SCRIPT B* lightson :: heyu lightson A
SCRIPT_MODE  SCRIPTS       # SCRIPTS  HEYUHELPER 
LONGITUDE         W079:16      # [degrees:minutes East or West of Greenwich]
LATITUDE          N43:78       # [degrees:minutes North or South of equator]
TIMER_LOOPCOUNT  57060393
```

**Comment by tommyd75** [comment]
So everything works fine except the engine doesn't start by itself when I reboot so I have to start it myself.
If I don't start it home bridge errors out like this.

Heyu onstate function failed: Error: Command failed: /usr/local/bin/heyu onstate K6
State engine is not running.


My config file looks like this.....

TTY	/dev/ttyS0

HOUSECODE K              


ALIAS  front_entry_light        K6   StdLM

START_ENGINE AUTO

**Comment by NorthernMan54** [comment]
On my raspberryPI I automatically start heyu when it boots up, similar to how you can start homebridge automatically when it starts.   Are you auto starting heyu on boot?

**Comment by tommyd75** [comment]
No I don’t think I have Heyu starting automatically, although I do have homebridge starting at boot. Is there a quick tutorial you can point me to?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NorthernMan54** [comment]
A quick google shows this

https://cylkedowney.wordpress.com/2017/05/19/starting-heyu-using-systemd/
